/**
 * Hotels Data - HomeComing 2025
 * 
 * Hotels used by the tour, linked to specific cities/events.
 */

import type { Hotel } from './types'

export const hotels: Hotel[] = [
  {
    id: 'hotel-1',
    organizationId: 'org-1',
    name: 'Delta Hotels by Marriott Moncton',
    address: '100 Main St',
    city: 'Moncton',
    state: 'NB',
    postalCode: 'E1C 1B8',
    phone: '(506) 854-4344',
    email: 'reservations@deltamoncton.com',
    contactName: 'Front Desk Manager',
    confirmationNumber: 'CONF-1000',
    distanceToVenue: '2.0 km',
    travelTimeToVenue: '8 mins',
    busParking: 'Yes',
    parkingNotes: 'Ample bus parking in rear lot',
    amenities: 'WiFi, Gym, Restaurant, Room Service',
    notes: 'Conveniently located downtown',
  },
  {
    id: 'hotel-2',
    organizationId: 'org-1',
    name: 'Best Western Glengarry',
    address: '150 Willow St',
    city: 'Truro',
    state: 'NS',
    postalCode: 'B2N 4Z6',
    phone: '(902) 893-4311',
    contactName: 'Hotel Manager',
    confirmationNumber: 'CONF-1001',
    distanceToVenue: '3.5 km',
    travelTimeToVenue: '10 mins',
    busParking: 'Yes',
    amenities: 'WiFi, Continental Breakfast, Pool',
  },
  {
    id: 'hotel-3',
    organizationId: 'org-1',
    name: "Sheraton Hotel Newfoundland",
    address: '115 Cavendish Square',
    city: "St. John's",
    state: 'NL',
    postalCode: 'A1C 3K2',
    phone: '(709) 726-4980',
    contactName: 'Group Sales',
    confirmationNumber: 'CONF-1002',
    distanceToVenue: '1.5 km',
    travelTimeToVenue: '5 mins',
    busParking: 'Limited - coordinate in advance',
    amenities: 'WiFi, Gym, Restaurant, Spa',
    notes: 'Walking distance to downtown',
  },
  {
    id: 'hotel-4',
    organizationId: 'org-1',
    name: 'Fairmont Château Laurier',
    address: '1 Rideau St',
    city: 'Ottawa',
    state: 'ON',
    postalCode: 'K1N 8S7',
    phone: '(613) 241-1414',
    confirmationNumber: 'CONF-1003',
    distanceToVenue: '8 km',
    travelTimeToVenue: '20 mins',
    busParking: 'No - use off-site parking',
    amenities: 'WiFi, Pool, Spa, Fine Dining',
    notes: 'Historic landmark hotel',
  },
  {
    id: 'hotel-5',
    organizationId: 'org-1',
    name: 'Holiday Inn Oshawa',
    address: '1011 Bloor St E',
    city: 'Oshawa',
    state: 'ON',
    postalCode: 'L1H 7K6',
    phone: '(905) 576-5101',
    confirmationNumber: 'CONF-1004',
    distanceToVenue: '4 km',
    travelTimeToVenue: '12 mins',
    busParking: 'Yes',
  },
  {
    id: 'hotel-6',
    organizationId: 'org-1',
    name: 'Best Western Inn On The Bay',
    address: '1800 2nd Ave E',
    city: 'Owen Sound',
    state: 'ON',
    postalCode: 'N4K 2J2',
    phone: '(519) 371-9200',
    confirmationNumber: 'CONF-1005',
  },
  {
    id: 'hotel-7',
    organizationId: 'org-1',
    name: 'Delta Hotels London Armouries',
    address: '325 Dundas St',
    city: 'London',
    state: 'ON',
    postalCode: 'N6B 1T9',
    phone: '(519) 679-6111',
    confirmationNumber: 'CONF-1006',
  },
  {
    id: 'hotel-8',
    organizationId: 'org-1',
    name: 'Holiday Inn Peterborough',
    address: '150 George St N',
    city: 'Peterborough',
    state: 'ON',
    postalCode: 'K9J 3G5',
    phone: '(705) 743-1144',
    confirmationNumber: 'CONF-1007',
  },
  {
    id: 'hotel-9',
    organizationId: 'org-1',
    name: 'Crowne Plaza Kitchener',
    address: '105 King St E',
    city: 'Kitchener',
    state: 'ON',
    postalCode: 'N2G 2K8',
    phone: '(519) 744-4141',
    confirmationNumber: 'CONF-1008',
  },
  {
    id: 'hotel-10',
    organizationId: 'org-1',
    name: 'Marriott Fallsview',
    address: '6755 Fallsview Blvd',
    city: 'Niagara Falls',
    state: 'ON',
    postalCode: 'L2G 3W7',
    phone: '(905) 357-7300',
    confirmationNumber: 'CONF-1009',
    amenities: 'WiFi, Pool, Spa, Restaurant',
  },
  {
    id: 'hotel-11',
    organizationId: 'org-1',
    name: 'Fort Chicken Hotel',
    address: '1 Market Square',
    city: 'Thunder Bay',
    state: 'ON',
    postalCode: 'P7A 1K4',
    phone: '(807) 345-2411',
    confirmationNumber: 'CONF-1010',
  },
  {
    id: 'hotel-12',
    organizationId: 'org-1',
    name: 'Fort Garry Hotel',
    address: '222 Broadway',
    city: 'Winnipeg',
    state: 'MB',
    postalCode: 'R3C 0R3',
    phone: '(204) 942-8251',
    confirmationNumber: 'CONF-1011',
    notes: 'Historic hotel, great restaurant',
  },
  {
    id: 'hotel-13',
    organizationId: 'org-1',
    name: 'Victoria Inn Brandon',
    address: '3550 Victoria Ave',
    city: 'Brandon',
    state: 'MB',
    postalCode: 'R7B 2R4',
    phone: '(204) 725-1532',
    confirmationNumber: 'CONF-1012',
  },
  {
    id: 'hotel-14',
    organizationId: 'org-1',
    name: 'Saskatoon Inn',
    address: '2002 Airport Dr',
    city: 'Saskatoon',
    state: 'SK',
    postalCode: 'S7L 6M4',
    phone: '(306) 242-1440',
    confirmationNumber: 'CONF-1013',
    busParking: 'Yes - large lot',
  },
  {
    id: 'hotel-15',
    organizationId: 'org-1',
    name: 'Delta Regina',
    address: '1919 Saskatchewan Dr',
    city: 'Regina',
    state: 'SK',
    postalCode: 'S4P 4H2',
    phone: '(306) 525-5255',
    confirmationNumber: 'CONF-1014',
  },
  {
    id: 'hotel-16',
    organizationId: 'org-1',
    name: 'Fairmont Palliser',
    address: '133 9 Ave SW',
    city: 'Calgary',
    state: 'AB',
    postalCode: 'T2P 2M3',
    phone: '(403) 262-1234',
    confirmationNumber: 'CONF-1015',
  },
  {
    id: 'hotel-17',
    organizationId: 'org-1',
    name: 'Red Deer Lodge',
    address: '4311 49 Ave',
    city: 'Red Deer',
    state: 'AB',
    postalCode: 'T4N 5Y7',
    phone: '(403) 346-8841',
    confirmationNumber: 'CONF-1016',
  },
  {
    id: 'hotel-18',
    organizationId: 'org-1',
    name: 'Fairmont Hotel Macdonald',
    address: '10065 100 St NW',
    city: 'Edmonton',
    state: 'AB',
    postalCode: 'T5J 0N6',
    phone: '(780) 424-5181',
    confirmationNumber: 'CONF-1017',
  },
  {
    id: 'hotel-19',
    organizationId: 'org-1',
    name: 'Delta Grand Okanagan',
    address: '1310 Water St',
    city: 'Kelowna',
    state: 'BC',
    postalCode: 'V1Y 9P3',
    phone: '(250) 763-4500',
    confirmationNumber: 'CONF-1018',
  },
  {
    id: 'hotel-20',
    organizationId: 'org-1',
    name: 'Coast Kamloops',
    address: '1250 Rogers Way',
    city: 'Kamloops',
    state: 'BC',
    postalCode: 'V1S 1N5',
    phone: '(250) 828-6660',
    confirmationNumber: 'CONF-1019',
  },
  {
    id: 'hotel-21',
    organizationId: 'org-1',
    name: 'Coast Bastion Hotel',
    address: '11 Bastion St',
    city: 'Nanaimo',
    state: 'BC',
    postalCode: 'V9R 6E4',
    phone: '(250) 753-6601',
    confirmationNumber: 'CONF-1020',
  },
  {
    id: 'hotel-22',
    organizationId: 'org-1',
    name: 'Best Western Austrian Chalet',
    address: '462 St Julien St',
    city: 'Campbell River',
    state: 'BC',
    postalCode: 'V9W 2H8',
    phone: '(250) 923-4231',
    confirmationNumber: 'CONF-1021',
  },
  {
    id: 'hotel-23',
    organizationId: 'org-1',
    name: 'Ramada Abbotsford',
    address: '36035 North Parallel Rd',
    city: 'Abbotsford',
    state: 'BC',
    postalCode: 'V3G 2C6',
    phone: '(604) 870-1050',
    confirmationNumber: 'CONF-1022',
  },
  {
    id: 'hotel-24',
    organizationId: 'org-1',
    name: 'Prestige Rocky Mountain Resort',
    address: '209 Van Horne St S',
    city: 'Cranbrook',
    state: 'BC',
    postalCode: 'V1C 6R2',
    phone: '(250) 417-0444',
    confirmationNumber: 'CONF-1023',
  },
]

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getHotelById(id: string): Hotel | undefined {
  return hotels.find(h => h.id === id)
}

export function getHotelsByCity(city: string): Hotel[] {
  return hotels.filter(h => h.city.toLowerCase() === city.toLowerCase())
}
