/**
 * Venues Data - HomeComing 2025
 * 
 * All venues used by the tour, with consistent IDs that events reference.
 */

import type { Venue } from './types'

export const venues: Venue[] = [
  {
    id: 'venue-1',
    organizationId: 'org-1',
    name: 'Casino New Brunswick',
    type: 'Casino',
    address: '21 Casino Dr.',
    city: 'Moncton',
    state: 'NB',
    postalCode: 'E1G 0R7',
    country: 'Canada',
    phone: '(877) 859-7775',
    website: 'https://greatcanadian.com/destinations/newbrunswick/moncton/',
    venueContactName: 'Event Coordinator',
    capacity: 1701,
    stageDimensions: '40x20ft',
    loadInInfo: '1 Dock, ground level access',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    powerInfo: '2 x 50A CAM-LOK',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    merchSplit: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
  },
  {
    id: 'venue-2',
    organizationId: 'org-1',
    name: 'Rath Eastlink Community Centre',
    type: 'Arena',
    address: '625 Abenaki Rd',
    city: 'Truro',
    state: 'NS',
    postalCode: 'B2N 0G6',
    country: 'Canada',
    phone: '(902) 893-2224',
    website: 'https://www.ratheastlinkcommunitycentre.ca/',
    venueContactName: 'Event Coordinator',
    capacity: 1796,
    stageDimensions: '40x40ft',
    loadInInfo: '1 Dock, ground level access',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    powerInfo: '2 x 50A CAM-LOK',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    merchSplit: '20% House / 80% Artist',
    laundryInfo: 'On-site washer/dryer',
    runnerInfo: '1 Runner available from 10am',
  },
  {
    id: 'venue-3',
    organizationId: 'org-1',
    name: 'Holy Heart Theatre',
    type: 'Theatre',
    address: '55 Bonaventure Ave',
    city: "St. John's",
    state: 'NL',
    postalCode: 'A1C 3Z3',
    country: 'Canada',
    phone: '(709) 579-4424',
    website: 'https://holyheart.ca/',
    venueContactName: 'Theatre Manager',
    capacity: 1000,
    stageDimensions: '35x25ft',
    loadInInfo: 'Rear loading, ramp access',
    dressingRoomInfo: '4 Rooms, 2 Private',
    wifiInfo: 'SSID: HHT_Guest, PW: theatre2025',
    powerInfo: '3 x 60A',
    busParking: 'Street parking, coordinate in advance',
    parkingInstructions: 'Load in via back alley off Military Rd',
    merchSplit: '15% House / 85% Artist',
  },
  {
    id: 'venue-4',
    organizationId: 'org-1',
    name: 'Meridian Theatres at Centrepointe',
    type: 'Theatre',
    address: '101 Centrepointe Dr',
    city: 'Ottawa',
    state: 'ON',
    postalCode: 'K2G 5K7',
    country: 'Canada',
    phone: '(613) 580-2700',
    website: 'https://meridiancentrepointe.com/',
    venueContactName: 'Production Manager',
    capacity: 955,
    stageDimensions: '42x30ft',
    loadInInfo: 'Dock with hydraulic lift',
    dressingRoomInfo: '6 Rooms, star dressing room available',
    wifiInfo: 'SSID: Meridian_Guest',
    powerInfo: '200A 3-phase',
  },
  {
    id: 'venue-5',
    organizationId: 'org-1',
    name: 'Tribute Communities Centre',
    type: 'Arena',
    address: '99 Athol St E',
    city: 'Oshawa',
    state: 'ON',
    postalCode: 'L1H 1J8',
    country: 'Canada',
    phone: '(905) 433-1234',
    venueContactName: 'Event Services',
    capacity: 5100,
    stageDimensions: '60x40ft',
    loadInInfo: 'Multiple loading docks',
    dressingRoomInfo: '4 Locker rooms convertible',
    busParking: 'Dedicated bus lot',
  },
  {
    id: 'venue-6',
    organizationId: 'org-1',
    name: 'Harry Lumley Bayshore Community Centre',
    type: 'Arena',
    address: '1900 3rd Ave E',
    city: 'Owen Sound',
    state: 'ON',
    postalCode: 'N4K 2M5',
    country: 'Canada',
    phone: '(519) 371-3232',
    venueContactName: 'Facility Manager',
    capacity: 3500,
    stageDimensions: '48x32ft',
  },
  {
    id: 'venue-7',
    organizationId: 'org-1',
    name: 'Centennial Hall',
    type: 'Theatre',
    address: '550 Wellington St',
    city: 'London',
    state: 'ON',
    postalCode: 'N6A 3R4',
    country: 'Canada',
    phone: '(519) 672-1967',
    capacity: 1729,
  },
  {
    id: 'venue-8',
    organizationId: 'org-1',
    name: 'Showplace Performance Centre',
    type: 'Theatre',
    address: '290 George St N',
    city: 'Peterborough',
    state: 'ON',
    postalCode: 'K9J 3H1',
    country: 'Canada',
    phone: '(705) 742-7469',
    capacity: 647,
  },
  {
    id: 'venue-9',
    organizationId: 'org-1',
    name: 'Centre in the Square',
    type: 'Theatre',
    address: '101 Queen St N',
    city: 'Kitchener',
    state: 'ON',
    postalCode: 'N2H 6P7',
    country: 'Canada',
    phone: '(519) 578-1570',
    capacity: 2047,
  },
  {
    id: 'venue-10',
    organizationId: 'org-1',
    name: 'Fallsview Casino Resort',
    type: 'Casino',
    address: '6380 Fallsview Blvd',
    city: 'Niagara Falls',
    state: 'ON',
    postalCode: 'L2G 7X5',
    country: 'Canada',
    phone: '(888) 325-5788',
    capacity: 1500,
  },
  {
    id: 'venue-11',
    organizationId: 'org-1',
    name: 'Empire Theatre',
    type: 'Theatre',
    address: '321 Front St',
    city: 'Belleville',
    state: 'ON',
    postalCode: 'K8N 2Z9',
    country: 'Canada',
    phone: '(613) 969-0099',
    capacity: 700,
  },
  {
    id: 'venue-12',
    organizationId: 'org-1',
    name: 'Thunder Bay Community Auditorium',
    type: 'Theatre',
    address: '450 Beverly St',
    city: 'Thunder Bay',
    state: 'ON',
    postalCode: 'P7B 5W5',
    country: 'Canada',
    phone: '(807) 684-4444',
    capacity: 1500,
  },
  {
    id: 'venue-13',
    organizationId: 'org-1',
    name: 'Burton Cummings Theatre',
    type: 'Theatre',
    address: '364 Smith St',
    city: 'Winnipeg',
    state: 'MB',
    postalCode: 'R3B 2H2',
    country: 'Canada',
    phone: '(204) 956-1360',
    capacity: 1671,
  },
  {
    id: 'venue-14',
    organizationId: 'org-1',
    name: 'Western Manitoba Centennial Auditorium',
    type: 'Theatre',
    address: '205 9th St',
    city: 'Brandon',
    state: 'MB',
    postalCode: 'R7A 4A9',
    country: 'Canada',
    phone: '(204) 728-9510',
    capacity: 900,
  },
  {
    id: 'venue-15',
    organizationId: 'org-1',
    name: 'Anne Chicken Theatre',
    type: 'Theatre',
    address: '49 Smith St E',
    city: 'Yorkton',
    state: 'SK',
    postalCode: 'S3N 0H4',
    country: 'Canada',
    phone: '(306) 782-2936',
    capacity: 700,
  },
  {
    id: 'venue-16',
    organizationId: 'org-1',
    name: 'Bonnyville & District Centennial Centre',
    type: 'Arena',
    address: '4804 50 Ave',
    city: 'Bonnyville',
    state: 'AB',
    postalCode: 'T9N 2G8',
    country: 'Canada',
    phone: '(780) 826-3496',
    capacity: 1000,
  },
  {
    id: 'venue-17',
    organizationId: 'org-1',
    name: 'TCU Place',
    type: 'Theatre',
    address: '35 22nd St E',
    city: 'Saskatoon',
    state: 'SK',
    postalCode: 'S7K 0C8',
    country: 'Canada',
    phone: '(306) 975-7777',
    capacity: 2003,
  },
  {
    id: 'venue-18',
    organizationId: 'org-1',
    name: 'Conexus Arts Centre',
    type: 'Theatre',
    address: '200 Lakeshore Dr',
    city: 'Regina',
    state: 'SK',
    postalCode: 'S4S 7L3',
    country: 'Canada',
    phone: '(306) 525-9999',
    capacity: 2029,
  },
  {
    id: 'venue-19',
    organizationId: 'org-1',
    name: 'Co-op Place',
    type: 'Arena',
    address: '2055 21st Ave SE',
    city: 'Medicine Hat',
    state: 'AB',
    postalCode: 'T1A 3Y4',
    country: 'Canada',
    phone: '(403) 527-1234',
    capacity: 6500,
  },
  {
    id: 'venue-20',
    organizationId: 'org-1',
    name: 'Southern Alberta Jubilee Auditorium',
    type: 'Theatre',
    address: '1415 14 Ave NW',
    city: 'Calgary',
    state: 'AB',
    postalCode: 'T2N 1M4',
    country: 'Canada',
    phone: '(403) 297-8000',
    capacity: 2538,
  },
  {
    id: 'venue-21',
    organizationId: 'org-1',
    name: 'Red Deer Memorial Centre',
    type: 'Arena',
    address: '4501 47A Ave',
    city: 'Red Deer',
    state: 'AB',
    postalCode: 'T4N 6Z6',
    country: 'Canada',
    phone: '(403) 309-8411',
    capacity: 6500,
  },
  {
    id: 'venue-22',
    organizationId: 'org-1',
    name: 'Northern Alberta Jubilee Auditorium',
    type: 'Theatre',
    address: '11455 87 Ave NW',
    city: 'Edmonton',
    state: 'AB',
    postalCode: 'T6G 2T2',
    country: 'Canada',
    phone: '(780) 427-2760',
    capacity: 2538,
  },
  {
    id: 'venue-23',
    organizationId: 'org-1',
    name: 'Allan & Jean Chicken Chicken Centre',
    type: 'Theatre',
    address: '5004 52 St',
    city: 'Whitecourt',
    state: 'AB',
    postalCode: 'T7S 1N2',
    country: 'Canada',
    phone: '(780) 778-6300',
    capacity: 500,
  },
  {
    id: 'venue-24',
    organizationId: 'org-1',
    name: 'Kelowna Community Theatre',
    type: 'Theatre',
    address: '1375 Water St',
    city: 'Kelowna',
    state: 'BC',
    postalCode: 'V1Y 1J4',
    country: 'Canada',
    phone: '(250) 469-8940',
    capacity: 847,
  },
  {
    id: 'venue-25',
    organizationId: 'org-1',
    name: 'Sandman Centre',
    type: 'Arena',
    address: '300 Lorne St',
    city: 'Kamloops',
    state: 'BC',
    postalCode: 'V2C 1W3',
    country: 'Canada',
    phone: '(250) 828-3636',
    capacity: 5464,
  },
  {
    id: 'venue-26',
    organizationId: 'org-1',
    name: 'Port Theatre',
    type: 'Theatre',
    address: '125 Front St',
    city: 'Nanaimo',
    state: 'BC',
    postalCode: 'V9R 6Z4',
    country: 'Canada',
    phone: '(250) 754-8550',
    capacity: 800,
  },
  {
    id: 'venue-27',
    organizationId: 'org-1',
    name: 'Tidemark Theatre',
    type: 'Theatre',
    address: '1220 Shoppers Row',
    city: 'Campbell River',
    state: 'BC',
    postalCode: 'V9W 2C8',
    country: 'Canada',
    phone: '(250) 287-7465',
    capacity: 550,
  },
  {
    id: 'venue-28',
    organizationId: 'org-1',
    name: 'Cowichan Performing Arts Centre',
    type: 'Theatre',
    address: '2687 James St',
    city: 'Duncan',
    state: 'BC',
    postalCode: 'V9L 2X5',
    country: 'Canada',
    phone: '(250) 748-7529',
    capacity: 737,
  },
  {
    id: 'venue-29',
    organizationId: 'org-1',
    name: 'Abbotsford Centre',
    type: 'Arena',
    address: '33800 King Rd',
    city: 'Abbotsford',
    state: 'BC',
    postalCode: 'V2S 7M1',
    country: 'Canada',
    phone: '(604) 852-6446',
    capacity: 7500,
  },
  {
    id: 'venue-30',
    organizationId: 'org-1',
    name: 'Key City Theatre',
    type: 'Theatre',
    address: '1015 Baker St',
    city: 'Cranbrook',
    state: 'BC',
    postalCode: 'V1C 1A1',
    country: 'Canada',
    phone: '(250) 426-7006',
    capacity: 650,
  },
]

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getVenueById(id: string): Venue | undefined {
  return venues.find(v => v.id === id)
}

export function getVenuesByCity(city: string): Venue[] {
  return venues.filter(v => v.city.toLowerCase() === city.toLowerCase())
}

export function searchVenues(query: string): Venue[] {
  const q = query.toLowerCase()
  return venues.filter(v => 
    v.name.toLowerCase().includes(q) ||
    v.city.toLowerCase().includes(q) ||
    v.state.toLowerCase().includes(q)
  )
}
