export interface Venue {
  id: string;
  name: string;
  street: string;
  city: string;
  state: string;
  postalCode: string;
  phone: string;
  capacity: string;
  type: string;
  website: string;
  stageDimensions: string;
  dressingRoomInfo: string;
  loadingDockInfo: string;
  wifiInfo: string;
  merchPercent: string;
  merchContact: string;
  laundryInfo: string;
  busParking: string;
  parkingInstructions: string;
  shorePower: string;
  runnerInfo: string;
  notes: string;
  shows: string;
  venueContact: string;
}

export const venues: Venue[] = [
  {
    id: '1',
    name: 'Casino New Brunswick',
    street: '21 Casino Dr.',
    city: 'Moncton',
    state: 'NB',
    postalCode: 'E1G 0R7',
    phone: '(877) 859-7775',
    capacity: '1701',
    type: 'Casino',
    website: 'https://greatcanadian.com/destinations/newbrunswick/moncton/#centre',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/17 - Moncton NB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '2',
    name: 'Rath Eastlink Community Centre',
    street: '625 Abenaki Rd, Truro, NS B2N 0G6, Canada',
    city: 'Truro',
    state: 'NS',
    postalCode: 'B2N 0G6',
    phone: '(902) 893-2224',
    capacity: '1796',
    type: 'Sports Complex',
    website: 'https://www.ratheastlinkcommunitycentre.ca/',
    stageDimensions: '40x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/18 - Truro NS NS',
    venueContact: 'Event Coordinator'
  },
  {
    id: '3',
    name: 'Holy Heart Theatre',
    street: '55 Bonaventure Ave',
    city: 'St. John\'s ',
    state: 'NL',
    postalCode: 'A1C 3Z3',
    phone: '(709) 579-4424',
    capacity: '4452',
    type: 'Theater',
    website: 'https://holyhearttheatre.com/',
    stageDimensions: '50x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/20 - St. John\'s NL,10/21 - St. John\'s NL',
    venueContact: 'Event Coordinator'
  },
  {
    id: '4',
    name: 'Meridian Theatres at Centrepoint',
    street: '101 Centrepointe Dr',
    city: 'Nepean',
    state: 'ON',
    postalCode: 'K2G 5K7',
    phone: '(613) 580-2700',
    capacity: '3330',
    type: 'Theater',
    website: 'https://meridiancentrepointe.com/en',
    stageDimensions: '30x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/23 - Ottawa ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '5',
    name: 'Tribute Communities Centre',
    street: '99 Athol St E',
    city: 'Oshawa',
    state: 'ON',
    postalCode: 'L1H 1J8',
    phone: '(905) 438-8811',
    capacity: '4762',
    type: 'Multi-Purpose Hall',
    website: 'http://www.tributecommunitiescentre.com/',
    stageDimensions: '50x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/24 - Oshawa ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '6',
    name: 'Harry Lumley Bayshore Community Centre',
    street: '1900 3rd Ave E',
    city: 'Owen Sound ',
    state: 'ON',
    postalCode: 'N4K 0H6',
    phone: '(519) 376-3594',
    capacity: '4564',
    type: 'Multi-Purpose Hall',
    website: 'http://www.thebayshore.ca/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/25 - Owen Sound ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '7',
    name: 'Centennial Concert Hall',
    street: '550 Wellington St',
    city: 'London',
    state: 'ON',
    postalCode: 'N6A 3P9',
    phone: '(519) 672-1967',
    capacity: '2075',
    type: 'Concert Hall',
    website: 'http://centennialhall.london.ca/',
    stageDimensions: '30x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/27 - London ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '8',
    name: 'Showplace Perf. Centre',
    street: '290 George St N',
    city: 'Peterborough',
    state: 'ON',
    postalCode: 'K9J 3H2',
    phone: '(705) 742-7469',
    capacity: '1979',
    type: 'Performing Arts Center',
    website: 'http://www.showplace.org/',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/28 - Peterborough ON,10/29 - Peterborough ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '9',
    name: 'Centre in the Square',
    street: '101 Queen St N',
    city: 'Kitchener',
    state: 'ON',
    postalCode: 'N2H 6P7',
    phone: '(519) 578-1570',
    capacity: '1853',
    type: 'Performing Arts Center',
    website: 'https://centreinthesquare.com/',
    stageDimensions: '40x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '10/30 - Kitchener ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '10',
    name: 'Fallsview Casino Resort',
    street: '6380 Fallsview Blvd',
    city: 'Niagara Falls',
    state: 'ON',
    postalCode: 'L2G 7X5',
    phone: '(888) 325-5788',
    capacity: '2075',
    type: 'Casino',
    website: 'https://fallsviewcasinoresort.com/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/1 - Niagara Falls ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '11',
    name: 'The Empire Theatre',
    street: '321 Front St',
    city: 'Belleville',
    state: 'ON',
    postalCode: 'K8N 2Z9',
    phone: '(613) 969-0099',
    capacity: '1361',
    type: 'Performing Arts Center',
    website: 'http://www.theempiretheatre.com/',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/2 - Belleville ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '12',
    name: 'Thunder Bay Community Auditorium',
    street: '1 Paul Shaffer Dr',
    city: 'Thunder Bay',
    state: 'ON',
    postalCode: 'P7B 6C7',
    phone: '(807) 684-4444',
    capacity: '2729',
    type: 'Concert Hall',
    website: 'http://www.tbca.com/',
    stageDimensions: '30x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/5 - Thunder Bay ON',
    venueContact: 'Event Coordinator'
  },
  {
    id: '13',
    name: 'Burton Cummings Theatre',
    street: '364 Smith St',
    city: 'Winnipeg',
    state: 'MB',
    postalCode: 'R3B 2H2',
    phone: '(204) 987-7825',
    capacity: '2799',
    type: 'Performing Arts Center',
    website: 'https://www.burtoncummingstheatre.ca/',
    stageDimensions: '30x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/7 - Winnipeg MB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '14',
    name: 'Western Manitoba Centennial Auditorium',
    street: '205 20th St',
    city: 'Brandon',
    state: 'MB',
    postalCode: 'R7B 1L6',
    phone: '(204) 728-9510',
    capacity: '4166',
    type: 'Ballroom',
    website: 'http://www.wmca.ca/',
    stageDimensions: '30x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/8 - Brandon MB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '15',
    name: 'Anne Portnuff Theatre',
    street: '150 Gladstone Ave N',
    city: 'Yorkton',
    state: 'SK',
    postalCode: 'S3N 2A8',
    phone: '555-012-3456',
    capacity: '601',
    type: 'Concert Hall',
    website: 'https://www.venue-example.com',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/9 - Yorkton SK',
    venueContact: 'Event Coordinator'
  },
  {
    id: '16',
    name: 'Bonnyville & District Centennial Centre',
    street: '4313 50 Ave',
    city: 'Bonnyville',
    state: 'AB',
    postalCode: 'T9N 0B4',
    phone: '(780) 812-3400',
    capacity: '2487',
    type: 'Multi-Purpose Hall',
    website: 'http://www.centennialcentre.ca/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/12 - Bonnyville AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '17',
    name: 'TCU Place',
    street: '35 22 St E',
    city: 'Saskatoon',
    state: 'SK',
    postalCode: 'S7K 0C8',
    phone: '(306) 975-7777',
    capacity: '2151',
    type: 'Conference Center',
    website: 'http://tcuplace.com/',
    stageDimensions: '50x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/13 - Saskatoon SK',
    venueContact: 'Event Coordinator'
  },
  {
    id: '18',
    name: 'Conexus Arts Centre',
    street: '200 Lakeshore Dr',
    city: 'Regina',
    state: 'SK',
    postalCode: 'S4S 7L3',
    phone: '(306) 525-9999',
    capacity: '1706',
    type: 'Performing Arts Center',
    website: 'http://www.conexusartscentre.ca/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/14 - Regina SK',
    venueContact: 'Event Coordinator'
  },
  {
    id: '19',
    name: 'Co-Op Place',
    street: '2802 Box Spgs Wy NW',
    city: 'Medicine Hat',
    state: 'AB',
    postalCode: 'T1C 0H3',
    phone: '(403) 905-0055',
    capacity: '3335',
    type: 'Arena',
    website: 'http://coopplace.ca/',
    stageDimensions: '30x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/15 - Medicine Hat AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '20',
    name: 'Southern Alberta Jubilee Auditorium',
    street: '1415 14 Ave NW',
    city: 'Calgary',
    state: 'AB',
    postalCode: 'T2N 1M4',
    phone: '(403) 297-8000',
    capacity: '2433',
    type: 'Auditorium',
    website: 'http://www.jubileeauditorium.com/',
    stageDimensions: '40x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/16 - Calgary AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '21',
    name: 'Red Deer Memorial Centre',
    street: '4214 58 St',
    city: 'Red Deer',
    state: 'AB',
    postalCode: 'T4N 2L6',
    phone: '(403) 347-8111',
    capacity: '1729',
    type: 'Performing Arts Center',
    website: 'http://reddeermemorialcentre.net/',
    stageDimensions: '30x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/18 - Red Deer AB,11/19 - Red Deer AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '22',
    name: 'Northern Alberta Jubilee Auditorium',
    street: '11455 87 Ave NW',
    city: 'Edmonton',
    state: 'AB',
    postalCode: 'T6G 2T2',
    phone: '(780) 427-2760',
    capacity: '2860',
    type: 'Auditorium',
    website: 'http://www.jubileeauditorium.com/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/20 - Edmonton AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '23',
    name: 'Allan & Jean Millar Centre',
    street: '58 Sunset Blvd',
    city: 'Whitecourt',
    state: 'AB',
    postalCode: 'T7S 1N6',
    phone: '(780) 778-3637',
    capacity: '3206',
    type: 'Multi-Purpose Hall',
    website: 'http://www.whitecourt.ca/',
    stageDimensions: '30x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/21 - Whitecourt AB',
    venueContact: 'Event Coordinator'
  },
  {
    id: '24',
    name: 'Kelowna Community Theatre',
    street: '1375 Water St',
    city: 'Kelowna',
    state: 'BC',
    postalCode: 'V1Y 0B4',
    phone: '(250) 469-8944',
    capacity: '3448',
    type: 'Theater',
    website: 'https://theatre.kelowna.ca/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/22 - Kelowna BC,11/23 - Kelowna BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '25',
    name: 'Sandman Centre',
    street: '300 Lorne St',
    city: 'Kamloops',
    state: 'BC',
    postalCode: 'V2C 1W3',
    phone: '(250) 828-3492',
    capacity: '3836',
    type: 'Arena',
    website: 'http://www.sandmancentre.com/',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/25 - Kamloops BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '26',
    name: 'Port Theatre',
    street: '125 Front St',
    city: 'Nanaimo',
    state: 'BC',
    postalCode: 'V9R 6Z4',
    phone: '(250) 754-8550',
    capacity: '2704',
    type: 'Performing Arts Center',
    website: 'http://www.porttheatre.com/',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/26 - Nanaimo BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '27',
    name: 'Tidemark Theatre',
    street: '1220 Shoppers Row',
    city: 'Campbell River ',
    state: 'BC',
    postalCode: 'V9W 2C8',
    phone: '(250) 287-7465',
    capacity: '2064',
    type: 'Performing Arts Center',
    website: 'http://tidemarktheatre.com/',
    stageDimensions: '30x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/27 - Campbell River BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '28',
    name: 'Cowichan Performing Arts Centre',
    street: '2687 James St',
    city: 'Duncan',
    state: 'BC',
    postalCode: 'V9L 2X5',
    phone: '(250) 746-2722',
    capacity: '1785',
    type: 'Performing Arts Center',
    website: 'http://cowichanpac.ca/',
    stageDimensions: '40x20ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/28 - Duncan BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '29',
    name: 'Royal Theatre',
    street: '805 Broughton St',
    city: 'Victoria',
    state: 'BC',
    postalCode: 'V8W 1E5',
    phone: '(250) 386-6121',
    capacity: '2549',
    type: 'Theater',
    website: 'http://www.rmts.bc.ca/',
    stageDimensions: '50x30ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '11/29 - Victoria BC,11/30 - Victoria BC',
    venueContact: 'Event Coordinator'
  },
  {
    id: '30',
    name: 'The Orpheum',
    street: '601 Smithe St',
    city: 'Vancouver',
    state: 'BC',
    postalCode: 'V6B 3L4',
    phone: '(604) 665-3035',
    capacity: '2774',
    type: 'Theater',
    website: 'https://vancouvercivictheatres.com/venues/the-orpheum/',
    stageDimensions: '40x40ft',
    dressingRoomInfo: '3 Rooms, 1 Private, showers available',
    loadingDockInfo: '1 Dock, ground level access',
    wifiInfo: 'SSID: Venue_Guest, PW: showtime2025',
    merchPercent: '20% House / 80% Artist',
    merchContact: 'Merch Manager',
    laundryInfo: 'On-site washer/dryer',
    busParking: 'Parking for 3 buses behind venue',
    parkingInstructions: 'Enter via alleyway on East side',
    shorePower: '2 x 50A CAM-LOK',
    runnerInfo: '1 Runner available from 10am',
    notes: 'Standard venue terms apply',
    shows: '12/1 - Vancouver BC',
    venueContact: 'Event Coordinator'
  }
];