export interface DayEvent {
  id: string
  date: string
  dayOfWeek: string
  dateShort: string
  eventName?: string
  location?: string
  venue?: string
  isEmpty: boolean
  status: string
  city: string
  state: string
  country: string
  timeZone: string
  dayType: string
}

export const daysEvents: DayEvent[] = [
  {
    id: '1',
    date: '2025-10-15',
    dayOfWeek: 'WED',
    dateShort: '10/15',
    status: 'confirmed',
    city: 'Moncton',
    state: 'NB',
    country: 'Canada',
    timeZone: 'Atlantic',
    dayType: 'Travel Day',
    eventName: 'Travel Day - Moncton',
    location: 'Moncton, NB',
    venue: '',
    isEmpty: true
  },
  {
    id: '2',
    date: '2025-10-16',
    dayOfWeek: 'THU',
    dateShort: '10/16',
    status: 'confirmed',
    city: 'Moncton',
    state: 'NB',
    country: 'Canada',
    timeZone: 'Atlantic',
    dayType: 'Rehearsal Day',
    eventName: 'Moncton NB',
    location: 'Moncton, NB',
    venue: '',
    isEmpty: false
  },
  {
    id: '3',
    date: '2025-10-17',
    dayOfWeek: 'FRI',
    dateShort: '10/17',
    status: 'confirmed',
    city: 'Moncton',
    state: 'NB',
    country: 'Canada',
    timeZone: 'Atlantic',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Casino New Brunswick',
    location: 'Moncton, NB',
    venue: 'Casino New Brunswick',
    isEmpty: false
  },
  {
    id: '4',
    date: '2025-10-18',
    dayOfWeek: 'SAT',
    dateShort: '10/18',
    status: 'confirmed',
    city: 'Truro NS',
    state: 'NS',
    country: 'Canada',
    timeZone: 'Atlantic',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Rath Eastlink Community Centre',
    location: 'Truro NS, NS',
    venue: 'Rath Eastlink Community Centre',
    isEmpty: false
  },
  {
    id: '5',
    date: '2025-10-19',
    dayOfWeek: 'SUN',
    dateShort: '10/19',
    status: 'confirmed',
    city: 'Truro NS',
    state: 'NS',
    country: 'Canada',
    timeZone: 'Atlantic',
    dayType: 'Travel Day',
    eventName: 'Travel Day - Truro NS',
    location: 'Truro NS, NS',
    venue: '',
    isEmpty: true
  },
  {
    id: '6',
    date: '2025-10-20',
    dayOfWeek: 'MON',
    dateShort: '10/20',
    status: 'confirmed',
    city: 'St. John\'s',
    state: 'NL',
    country: 'Canada',
    timeZone: 'Newfoundland',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Holy Heart Theatre',
    location: 'St. John\'s, NL',
    venue: 'Holy Heart Theatre',
    isEmpty: false
  },
  {
    id: '7',
    date: '2025-10-21',
    dayOfWeek: 'TUE',
    dateShort: '10/21',
    status: 'confirmed',
    city: 'St. John\'s',
    state: 'NL',
    country: 'Canada',
    timeZone: 'Newfoundland',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Holy Heart Theatre',
    location: 'St. John\'s, NL',
    venue: 'Holy Heart Theatre',
    isEmpty: false
  },
  {
    id: '8',
    date: '2025-10-22',
    dayOfWeek: 'WED',
    dateShort: '10/22',
    status: 'confirmed',
    city: 'St. John\'s',
    state: 'NL',
    country: 'Canada',
    timeZone: 'Newfoundland',
    dayType: 'Travel Day',
    eventName: 'Travel Day - St. John\'s',
    location: 'St. John\'s, NL',
    venue: '',
    isEmpty: true
  },
  {
    id: '9',
    date: '2025-10-23',
    dayOfWeek: 'THU',
    dateShort: '10/23',
    status: 'confirmed',
    city: 'Ottawa',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Meridian Theatres at Centrepointe',
    location: 'Ottawa, ON',
    venue: 'Meridian Theatres at Centrepointe',
    isEmpty: false
  },
  {
    id: '10',
    date: '2025-10-24',
    dayOfWeek: 'FRI',
    dateShort: '10/24',
    status: 'confirmed',
    city: 'Oshawa',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Tribute Communities Centre',
    location: 'Oshawa, ON',
    venue: 'Tribute Communities Centre',
    isEmpty: false
  },
  {
    id: '11',
    date: '2025-10-25',
    dayOfWeek: 'SAT',
    dateShort: '10/25',
    status: 'confirmed',
    city: 'Owen Sound',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Harry Lumley Bayshore Arena',
    location: 'Owen Sound, ON',
    venue: 'Harry Lumley Bayshore Arena',
    isEmpty: false
  },
  {
    id: '12',
    date: '2025-10-26',
    dayOfWeek: 'SUN',
    dateShort: '10/26',
    status: 'confirmed',
    city: 'Owen Sound',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Day Off',
    eventName: 'Day Off - Owen Sound',
    location: 'Owen Sound, ON',
    venue: '',
    isEmpty: true
  },
  {
    id: '13',
    date: '2025-10-27',
    dayOfWeek: 'MON',
    dateShort: '10/27',
    status: 'confirmed',
    city: 'London',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Centennial Concert Hall',
    location: 'London, ON',
    venue: 'Centennial Concert Hall',
    isEmpty: false
  },
  {
    id: '14',
    date: '2025-10-28',
    dayOfWeek: 'TUE',
    dateShort: '10/28',
    status: 'confirmed',
    city: 'Peterborough',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Showplace Performance Centre',
    location: 'Peterborough, ON',
    venue: 'Showplace Performance Centre',
    isEmpty: false
  },
  {
    id: '15',
    date: '2025-10-29',
    dayOfWeek: 'WED',
    dateShort: '10/29',
    status: 'confirmed',
    city: 'Peterborough',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Showplace Performance Centre',
    location: 'Peterborough, ON',
    venue: 'Showplace Performance Centre',
    isEmpty: false
  },
  {
    id: '16',
    date: '2025-10-30',
    dayOfWeek: 'THU',
    dateShort: '10/30',
    status: 'confirmed',
    city: 'Kitchener',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Centre in the Square',
    location: 'Kitchener, ON',
    venue: 'Centre in the Square',
    isEmpty: false
  },
  {
    id: '17',
    date: '2025-10-31',
    dayOfWeek: 'FRI',
    dateShort: '10/31',
    status: 'confirmed',
    city: 'Kitchener',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Day Off',
    eventName: 'Day Off - Kitchener',
    location: 'Kitchener, ON',
    venue: '',
    isEmpty: true
  },
  {
    id: '18',
    date: '2025-11-01',
    dayOfWeek: 'SAT',
    dateShort: '11/01',
    status: 'confirmed',
    city: 'Niagara Falls',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at OLG Stage at Fallsview Casino',
    location: 'Niagara Falls, ON',
    venue: 'OLG Stage at Fallsview Casino',
    isEmpty: false
  },
  {
    id: '19',
    date: '2025-11-02',
    dayOfWeek: 'SUN',
    dateShort: '11/02',
    status: 'confirmed',
    city: 'Belleville',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Empire Theatre',
    location: 'Belleville, ON',
    venue: 'Empire Theatre',
    isEmpty: false
  },
  {
    id: '20',
    date: '2025-11-03',
    dayOfWeek: 'MON',
    dateShort: '11/03',
    status: 'confirmed',
    city: 'Belleville',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Day Off',
    eventName: 'Day Off - Belleville',
    location: 'Belleville, ON',
    venue: '',
    isEmpty: true
  },
  {
    id: '21',
    date: '2025-11-04',
    dayOfWeek: 'TUE',
    dateShort: '11/04',
    status: 'confirmed',
    city: 'Belleville',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Day Off',
    eventName: 'Day Off - Belleville',
    location: 'Belleville, ON',
    venue: '',
    isEmpty: true
  },
  {
    id: '22',
    date: '2025-11-05',
    dayOfWeek: 'WED',
    dateShort: '11/05',
    status: 'confirmed',
    city: 'Thunder Bay',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Thunder Bay Community Auditorium',
    location: 'Thunder Bay, ON',
    venue: 'Thunder Bay Community Auditorium',
    isEmpty: false
  },
  {
    id: '23',
    date: '2025-11-06',
    dayOfWeek: 'THU',
    dateShort: '11/06',
    status: 'confirmed',
    city: 'Thunder Bay',
    state: 'ON',
    country: 'Canada',
    timeZone: 'Eastern',
    dayType: 'Day Off',
    eventName: 'Day Off - Thunder Bay',
    location: 'Thunder Bay, ON',
    venue: '',
    isEmpty: true
  },
  {
    id: '24',
    date: '2025-11-07',
    dayOfWeek: 'FRI',
    dateShort: '11/07',
    status: 'confirmed',
    city: 'Winnipeg',
    state: 'MB',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Burton Cummings Theatre',
    location: 'Winnipeg, MB',
    venue: 'Burton Cummings Theatre',
    isEmpty: false
  },
  {
    id: '25',
    date: '2025-11-08',
    dayOfWeek: 'SAT',
    dateShort: '11/08',
    status: 'confirmed',
    city: 'Brandon',
    state: 'MB',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Western Manitoba Centennial Auditorium',
    location: 'Brandon, MB',
    venue: 'Western Manitoba Centennial Auditorium',
    isEmpty: false
  },
  {
    id: '26',
    date: '2025-11-09',
    dayOfWeek: 'SUN',
    dateShort: '11/09',
    status: 'confirmed',
    city: 'Yorkton',
    state: 'SK',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Anne Portnuff Theatre',
    location: 'Yorkton, SK',
    venue: 'Anne Portnuff Theatre',
    isEmpty: false
  },
  {
    id: '27',
    date: '2025-11-10',
    dayOfWeek: 'MON',
    dateShort: '11/10',
    status: 'confirmed',
    city: 'Yorkton',
    state: 'SK',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Day Off',
    eventName: 'Day Off - Yorkton',
    location: 'Yorkton, SK',
    venue: '',
    isEmpty: true
  },
  {
    id: '28',
    date: '2025-11-11',
    dayOfWeek: 'TUE',
    dateShort: '11/11',
    status: 'confirmed',
    city: 'Yorkton',
    state: 'SK',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Day Off',
    eventName: 'Day Off - Yorkton',
    location: 'Yorkton, SK',
    venue: '',
    isEmpty: true
  },
  {
    id: '29',
    date: '2025-11-12',
    dayOfWeek: 'WED',
    dateShort: '11/12',
    status: 'confirmed',
    city: 'Bonnyville',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Bonnyville & District Centennial Centre',
    location: 'Bonnyville, AB',
    venue: 'Bonnyville & District Centennial Centre',
    isEmpty: false
  },
  {
    id: '30',
    date: '2025-11-13',
    dayOfWeek: 'THU',
    dateShort: '11/13',
    status: 'confirmed',
    city: 'Saskatoon',
    state: 'SK',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at TCU Place',
    location: 'Saskatoon, SK',
    venue: 'TCU Place',
    isEmpty: false
  },
  {
    id: '31',
    date: '2025-11-14',
    dayOfWeek: 'FRI',
    dateShort: '11/14',
    status: 'confirmed',
    city: 'Regina',
    state: 'SK',
    country: 'Canada',
    timeZone: 'Central',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Conexus Arts Centre',
    location: 'Regina, SK',
    venue: 'Conexus Arts Centre',
    isEmpty: false
  },
  {
    id: '32',
    date: '2025-11-15',
    dayOfWeek: 'SAT',
    dateShort: '11/15',
    status: 'confirmed',
    city: 'Medicine Hat',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Co-op Place',
    location: 'Medicine Hat, AB',
    venue: 'Co-op Place',
    isEmpty: false
  },
  {
    id: '33',
    date: '2025-11-16',
    dayOfWeek: 'SUN',
    dateShort: '11/16',
    status: 'confirmed',
    city: 'Calgary',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Southern Alberta Jubilee Auditorium',
    location: 'Calgary, AB',
    venue: 'Southern Alberta Jubilee Auditorium',
    isEmpty: false
  },
  {
    id: '34',
    date: '2025-11-17',
    dayOfWeek: 'MON',
    dateShort: '11/17',
    status: 'confirmed',
    city: 'Calgary',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Travel Day',
    eventName: 'Travel Day - Calgary',
    location: 'Calgary, AB',
    venue: '',
    isEmpty: true
  },
  {
    id: '35',
    date: '2025-11-18',
    dayOfWeek: 'TUE',
    dateShort: '11/18',
    status: 'confirmed',
    city: 'Red Deer',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Red Deer Memorial Centre',
    location: 'Red Deer, AB',
    venue: 'Red Deer Memorial Centre',
    isEmpty: false
  },
  {
    id: '36',
    date: '2025-11-19',
    dayOfWeek: 'WED',
    dateShort: '11/19',
    status: 'confirmed',
    city: 'Red Deer',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Red Deer Memorial Centre',
    location: 'Red Deer, AB',
    venue: 'Red Deer Memorial Centre',
    isEmpty: false
  },
  {
    id: '37',
    date: '2025-11-20',
    dayOfWeek: 'THU',
    dateShort: '11/20',
    status: 'confirmed',
    city: 'Edmonton',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Northern Alberta Jubilee Auditorium',
    location: 'Edmonton, AB',
    venue: 'Northern Alberta Jubilee Auditorium',
    isEmpty: false
  },
  {
    id: '38',
    date: '2025-11-21',
    dayOfWeek: 'FRI',
    dateShort: '11/21',
    status: 'confirmed',
    city: 'Whitecourt',
    state: 'AB',
    country: 'Canada',
    timeZone: 'Mountain',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Allan & Jean Millar Centre',
    location: 'Whitecourt, AB',
    venue: 'Allan & Jean Millar Centre',
    isEmpty: false
  },
  {
    id: '39',
    date: '2025-11-22',
    dayOfWeek: 'SAT',
    dateShort: '11/22',
    status: 'confirmed',
    city: 'Kelowna',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Kelowna Community Theatre',
    location: 'Kelowna, BC',
    venue: 'Kelowna Community Theatre',
    isEmpty: false
  },
  {
    id: '40',
    date: '2025-11-23',
    dayOfWeek: 'SUN',
    dateShort: '11/23',
    status: 'confirmed',
    city: 'Kelowna',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Kelowna Community Theatre',
    location: 'Kelowna, BC',
    venue: 'Kelowna Community Theatre',
    isEmpty: false
  },
  {
    id: '41',
    date: '2025-11-24',
    dayOfWeek: 'MON',
    dateShort: '11/24',
    status: 'confirmed',
    city: 'Kelowna',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Travel Day',
    eventName: 'Travel Day - Kelowna',
    location: 'Kelowna, BC',
    venue: '',
    isEmpty: true
  },
  {
    id: '42',
    date: '2025-11-25',
    dayOfWeek: 'TUE',
    dateShort: '11/25',
    status: 'confirmed',
    city: 'Kamloops',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Sandman Centre',
    location: 'Kamloops, BC',
    venue: 'Sandman Centre',
    isEmpty: false
  },
  {
    id: '43',
    date: '2025-11-26',
    dayOfWeek: 'WED',
    dateShort: '11/26',
    status: 'confirmed',
    city: 'Nanaimo',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Port Theatre',
    location: 'Nanaimo, BC',
    venue: 'Port Theatre',
    isEmpty: false
  },
  {
    id: '44',
    date: '2025-11-27',
    dayOfWeek: 'THU',
    dateShort: '11/27',
    status: 'confirmed',
    city: 'Campbell River',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Tidemark Theatre',
    location: 'Campbell River, BC',
    venue: 'Tidemark Theatre',
    isEmpty: false
  },
  {
    id: '45',
    date: '2025-11-28',
    dayOfWeek: 'FRI',
    dateShort: '11/28',
    status: 'confirmed',
    city: 'Duncan',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Cowichan Performing Arts Centre',
    location: 'Duncan, BC',
    venue: 'Cowichan Performing Arts Centre',
    isEmpty: false
  },
  {
    id: '46',
    date: '2025-11-29',
    dayOfWeek: 'SAT',
    dateShort: '11/29',
    status: 'confirmed',
    city: 'Abbotsford',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Abbotsford Centre',
    location: 'Abbotsford, BC',
    venue: 'Abbotsford Centre',
    isEmpty: false
  },
  {
    id: '47',
    date: '2025-11-30',
    dayOfWeek: 'SUN',
    dateShort: '11/30',
    status: 'confirmed',
    city: 'Abbotsford',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'On Hold',
    eventName: '11/30',
    location: 'Abbotsford, BC',
    venue: '',
    isEmpty: true
  },
  {
    id: '48',
    date: '2025-12-01',
    dayOfWeek: 'MON',
    dateShort: '12/01',
    status: 'confirmed',
    city: 'Cranbrook',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Show Day',
    eventName: 'Paul Brandt & Terri Clark at Key City Theatre',
    location: 'Cranbrook, BC',
    venue: 'Key City Theatre',
    isEmpty: false
  },
  {
    id: '49',
    date: '2025-12-02',
    dayOfWeek: 'TUE',
    dateShort: '12/02',
    status: 'confirmed',
    city: 'Cranbrook',
    state: 'BC',
    country: 'Canada',
    timeZone: 'Pacific',
    dayType: 'Travel Day',
    eventName: 'Travel Day - Cranbrook',
    location: 'Cranbrook, BC',
    venue: '',
    isEmpty: true
  }
];
