export interface Person {
  id: string
  firstName: string
  lastName: string
  middleName?: string
  fullName: string
  role: string
  department: string
  email?: string
  phone?: string
  address?: string
  dob?: string
  company?: string
  tourId: string
  tourName?: string
  passportNumber?: string
  passportExpiration?: string
  passportCountry?: string
  nationality?: string
  emergencyContactName?: string
  emergencyContactRelationship?: string
  emergencyContactPhone?: string
  emergencyContactEmail?: string
  shirtSize?: string
  jacketSize?: string
  notes?: string
}

export const mockPeople: Person[] = [
  // --- DATA FROM CSV ---
  {
    id: "1",
    firstName: "Steve",
    lastName: "Coplan",
    middleName: "Chuck",
    fullName: "Steve Coplan",
    role: "Tour Manager",
    department: "Management",
    email: "steve@steve.com",
    phone: "615-555-1212",
    address: "1210 Glen Echo Dr Nashville TN 37215",
    dob: "",
    company: "",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "L",
    jacketSize: "L",
    notes: ""
  },
  {
    id: "2",
    firstName: "Elena",
    lastName: "Sherertz",
    middleName: "Lauren",
    fullName: "Elena Sherertz",
    role: "Stage Manager,Guitar Tech",
    department: "Management",
    email: "elena@elena.com",
    phone: "615-555-1498",
    address: "2416 Johnson Blvd, Nashville, TN, 37217",
    dob: "",
    company: "",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "M",
    jacketSize: "L",
    notes: ""
  },
  {
    id: "3",
    firstName: "Patrick",
    lastName: "Guay",
    middleName: "",
    fullName: "Patrick Guay",
    role: "Promoter Rep",
    department: "Management",
    email: "patrick@livenation.com",
    phone: "",
    address: "",
    dob: "",
    company: "Live Nation",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "4",
    firstName: "Alex",
    lastName: "Vyskocil",
    middleName: "",
    fullName: "Alex Vyskocil",
    role: "Production Assistant",
    department: "Production",
    email: "alex@livenation.com",
    phone: "",
    address: "",
    dob: "",
    company: "Live Nation",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "5",
    firstName: "Richard",
    lastName: "Sharpe",
    middleName: "",
    fullName: "Richard Sharpe",
    role: "Producer",
    department: "Production",
    email: "",
    phone: "",
    address: "",
    dob: "",
    company: "Richard Sharpe Productions",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "6",
    firstName: "Ante",
    lastName: "Zlomislic",
    middleName: "",
    fullName: "Ante Zlomislic",
    role: "Crew",
    department: "Production",
    email: "",
    phone: "",
    address: "",
    dob: "",
    company: "CONF",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "7",
    firstName: "Mark",
    lastName: "Rashotte",
    middleName: "",
    fullName: "Mark Rashotte",
    role: "Crew",
    department: "Production",
    email: "",
    phone: "",
    address: "",
    dob: "",
    company: "CONF",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "8",
    firstName: "Rob",
    lastName: "Waloschuk",
    middleName: "",
    fullName: "Rob Waloschuk",
    role: "Promoter",
    department: "Management",
    email: "",
    phone: "",
    address: "",
    dob: "",
    company: "Rob Waloschuk Promotions",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },
  {
    id: "9",
    firstName: "Gene",
    lastName: "Daniel",
    middleName: "",
    fullName: "Gene Daniel",
    role: "Crew",
    department: "Production",
    email: "",
    phone: "",
    address: "",
    dob: "",
    company: "CONF",
    tourId: "1",
    tourName: "",
    passportNumber: "",
    passportExpiration: "",
    passportCountry: "",
    nationality: "",
    emergencyContactName: "",
    emergencyContactRelationship: "",
    emergencyContactPhone: "",
    emergencyContactEmail: "",
    shirtSize: "",
    jacketSize: "",
    notes: ""
  },

  // --- SUPPLEMENTAL ROSTER DATA (Tours 1-6) ---
  {
    id: "10",
    firstName: "Marcus",
    lastName: "Miller",
    middleName: "M.",
    fullName: "Marcus Miller",
    role: "Production Manager",
    department: "Production",
    email: "marcus.miller@tourcrew.com",
    phone: "615-555-0010",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000010",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "11",
    firstName: "Sarah",
    lastName: "Jennings",
    middleName: "M.",
    fullName: "Sarah Jennings",
    role: "FOH Engineer",
    department: "Audio",
    email: "sarah.jennings@tourcrew.com",
    phone: "615-555-0011",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000011",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "12",
    firstName: "Kevin",
    lastName: "Watts",
    middleName: "M.",
    fullName: "Kevin Watts",
    role: "Monitor Engineer",
    department: "Audio",
    email: "kevin.watts@tourcrew.com",
    phone: "615-555-0012",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000012",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "13",
    firstName: "David",
    lastName: "Lee",
    middleName: "M.",
    fullName: "David Lee",
    role: "Drum Tech",
    department: "Backline",
    email: "david.lee@tourcrew.com",
    phone: "615-555-0013",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000013",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "14",
    firstName: "Rachel",
    lastName: "Green",
    middleName: "M.",
    fullName: "Rachel Green",
    role: "Lighting Director",
    department: "Lighting",
    email: "rachel.green@tourcrew.com",
    phone: "615-555-0014",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000014",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "15",
    firstName: "Sam",
    lastName: "Rivers",
    middleName: "M.",
    fullName: "Sam Rivers",
    role: "Video Director",
    department: "Video",
    email: "sam.rivers@tourcrew.com",
    phone: "615-555-0015",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000015",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "16",
    firstName: "Beth",
    lastName: "Dutton",
    middleName: "M.",
    fullName: "Beth Dutton",
    role: "Merch Manager",
    department: "Merch",
    email: "beth.dutton@tourcrew.com",
    phone: "615-555-0016",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000016",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "17",
    firstName: "Tom",
    lastName: "Hanks",
    middleName: "M.",
    fullName: "Tom Hanks",
    role: "Bus Driver 1",
    department: "Transportation",
    email: "tom.hanks@tourcrew.com",
    phone: "615-555-0017",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000017",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "18",
    firstName: "Jerry",
    lastName: "Riggs",
    middleName: "M.",
    fullName: "Jerry Riggs",
    role: "Bus Driver 2",
    department: "Transportation",
    email: "jerry.riggs@tourcrew.com",
    phone: "615-555-0018",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000018",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "19",
    firstName: "Lars",
    lastName: "Ulrich",
    middleName: "M.",
    fullName: "Lars Ulrich",
    role: "Truck Driver",
    department: "Transportation",
    email: "lars.ulrich@tourcrew.com",
    phone: "615-555-0019",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000019",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "20",
    firstName: "Slash",
    lastName: "Hudson",
    middleName: "M.",
    fullName: "Slash Hudson",
    role: "Drummer",
    department: "Band",
    email: "slash.hudson@tourcrew.com",
    phone: "615-555-0020",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000020",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "21",
    firstName: "Flea",
    lastName: "Balzary",
    middleName: "M.",
    fullName: "Flea Balzary",
    role: "Keyboards",
    department: "Band",
    email: "flea.balzary@tourcrew.com",
    phone: "615-555-0021",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000021",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "22",
    firstName: "Chick",
    lastName: "Corea",
    middleName: "M.",
    fullName: "Chick Corea",
    role: "Bass",
    department: "Band",
    email: "chick.corea@tourcrew.com",
    phone: "615-555-0022",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000022",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "23",
    firstName: "Buddy",
    lastName: "Emmons",
    middleName: "M.",
    fullName: "Buddy Emmons",
    role: "Steel Guitar",
    department: "Band",
    email: "buddy.emmons@tourcrew.com",
    phone: "615-555-0023",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000023",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "24",
    firstName: "Alison",
    lastName: "Krauss",
    middleName: "M.",
    fullName: "Alison Krauss",
    role: "Fiddle",
    department: "Band",
    email: "alison.krauss@tourcrew.com",
    phone: "615-555-0024",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "1",
    tourName: "HomeComing 2025",
    passportNumber: "A0000024",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },

  // --- REPEATING ROSTER PATTERN FOR TOURS 2, 3, 4, 5, 6 ---
  {
    id: "25",
    firstName: "Bob",
    lastName: "Rock",
    middleName: "M.",
    fullName: "Bob Rock",
    role: "Tour Manager",
    department: "Management",
    email: "bob.rock@tourcrew.com",
    phone: "615-555-0025",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "2",
    tourName: "Western Winds 2025",
    passportNumber: "A0000025",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  },
  {
    id: "114",
    firstName: "Paul",
    lastName: "McCartney",
    middleName: "M.",
    fullName: "Paul McCartney",
    role: "Fiddle",
    department: "Band",
    email: "paul.mccartney@tourcrew.com",
    phone: "615-555-0114",
    address: "456 Tour Ave, Nashville, TN 37203",
    dob: "1988-04-12",
    company: "Global Touring Group",
    tourId: "6",
    tourName: "Midnight Run 2022",
    passportNumber: "A0000114",
    passportExpiration: "2032-10-10",
    passportCountry: "USA",
    nationality: "American",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "555-000-0000",
    emergencyContactEmail: "jane.doe@example.com",
    shirtSize: "L",
    jacketSize: "XL",
    notes: " "
  }
];