export interface Event {
  id: string
  date: string
  location: string
  venue: string
  status: 'confirmed' | 'pending' | 'cancelled'
  capacity: number
  showTime: string
  advanceStatus: 'in-progress' | 'not-started' | 'completed'
  advanced: string
  loadIn: string
  soundCheck: string
  lunch: string
  doors: string
  setLength: string
  dinner: string
  curfew: string
  returnToHotelAfterSoundCheck: string
  returnToHotelAfterShow: string
  dayOfContact: string
  email: string
  phone: string
  promoter: string
  promoterPrimaryContact: string
  loadInDetails: string
  soundDetails: string
  lightDetails: string
  securityDetails: string
  cateringDetails: string
  lunchCount: string
  dinnerCount: string
  meetAndGreet: string
  notes: string
  hotels: string
  tixSold: string
  percentSold: string
  totalComps: string
  compsRemain: string
  compsUsed: string
}

export const events: Event[] = [
  {
    id: '1',
    date: 'Oct 17, 2025',
    location: 'Moncton NB',
    venue: 'Casino New Brunswick',
    status: 'confirmed',
    capacity: 5000,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '4000.0',
    percentSold: '80%',
    totalComps: '30.0',
    compsRemain: '26',
    compsUsed: '4'
  },
  {
    id: '2',
    date: 'Oct 18, 2025',
    location: 'Truro NS NS',
    venue: 'Rath Eastlink Community Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '3',
    date: 'Oct 20, 2025',
    location: "St. John\\'s NL",
    venue: 'Holy Heart Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '4',
    date: 'Oct 21, 2025',
    location: "St. John\\'s NL",
    venue: 'Holy Heart Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '5',
    date: 'Oct 23, 2025',
    location: 'Ottawa ON',
    venue: 'Meridian Theatres at Centrepoint',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '6',
    date: 'Oct 24, 2025',
    location: 'Oshawa ON',
    venue: 'Tribute Communities Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '7',
    date: 'Oct 25, 2025',
    location: 'Owen Sound ON',
    venue: 'Harry Lumley Bayshore Community Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '8',
    date: 'Oct 27, 2025',
    location: 'London ON',
    venue: 'Centennial Concert Hall',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '9',
    date: 'Oct 28, 2025',
    location: 'Peterborough ON',
    venue: 'Showplace Perf. Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '10',
    date: 'Oct 29, 2025',
    location: 'Peterborough ON',
    venue: 'Showplace Perf. Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '11',
    date: 'Oct 30, 2025',
    location: 'Kitchener ON',
    venue: 'Centre in the Square',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '12',
    date: 'Nov 01, 2025',
    location: 'Niagara Falls ON',
    venue: 'Fallsview Casino Resort',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '13',
    date: 'Nov 02, 2025',
    location: 'Belleville ON',
    venue: 'The Empire Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '14',
    date: 'Nov 05, 2025',
    location: 'Thunder Bay ON',
    venue: 'Thunder Bay Community Auditorium',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '15',
    date: 'Nov 07, 2025',
    location: 'Winnipeg MB',
    venue: 'Burton Cummings Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '16',
    date: 'Nov 08, 2025',
    location: 'Brandon MB',
    venue: 'Western Manitoba Centennial Auditorium',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '17',
    date: 'Nov 09, 2025',
    location: 'Yorkton SK',
    venue: 'Anne Portnuff Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '18',
    date: 'Nov 12, 2025',
    location: 'Bonnyville AB',
    venue: 'Bonnyville & District Centennial Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '19',
    date: 'Nov 13, 2025',
    location: 'Saskatoon SK',
    venue: 'TCU Place',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '20',
    date: 'Nov 14, 2025',
    location: 'Regina SK',
    venue: 'Conexus Arts Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '21',
    date: 'Nov 15, 2025',
    location: 'Medicine Hat AB',
    venue: 'Co-Op Place',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '22',
    date: 'Nov 16, 2025',
    location: 'Calgary AB',
    venue: 'Southern Alberta Jubilee Auditorium',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '23',
    date: 'Nov 18, 2025',
    location: 'Red Deer AB',
    venue: 'Red Deer Memorial Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '24',
    date: 'Nov 19, 2025',
    location: 'Red Deer AB',
    venue: 'Red Deer Memorial Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '25',
    date: 'Nov 20, 2025',
    location: 'Edmonton AB',
    venue: 'Northern Alberta Jubilee Auditorium',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '26',
    date: 'Nov 21, 2025',
    location: 'Whitecourt AB',
    venue: 'Allan & Jean Millar Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '27',
    date: 'Nov 22, 2025',
    location: 'Kelowna BC',
    venue: 'Kelowna Community Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '28',
    date: 'Nov 23, 2025',
    location: 'Kelowna BC',
    venue: 'Kelowna Community Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '29',
    date: 'Nov 25, 2025',
    location: 'Kamloops BC',
    venue: 'Sandman Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '30',
    date: 'Nov 26, 2025',
    location: 'Nanaimo BC',
    venue: 'Port Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '31',
    date: 'Nov 27, 2025',
    location: 'Campbell River BC',
    venue: 'Tidemark Theatre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '32',
    date: 'Nov 28, 2025',
    location: 'Duncan BC',
    venue: 'Cowichan Performing Arts Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '33',
    date: 'Nov 29, 2025',
    location: 'Abbotsford BC',
    venue: 'Abbotsford Centre',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  },
  {
    id: '34',
    date: 'Dec 01, 2025',
    location: 'Cranbrook BC',
    venue: 'Western Financial Place',
    status: 'confirmed',
    capacity: 0,
    showTime: '8:00pm',
    advanceStatus: 'not-started',
    advanced: 'Not Started',
    loadIn: '',
    soundCheck: '',
    lunch: '',
    doors: '',
    setLength: '',
    dinner: '',
    curfew: '',
    returnToHotelAfterSoundCheck: '',
    returnToHotelAfterShow: '',
    dayOfContact: '',
    email: '',
    phone: '',
    promoter: '',
    promoterPrimaryContact: '',
    loadInDetails: '',
    soundDetails: '',
    lightDetails: '',
    securityDetails: '',
    cateringDetails: '',
    lunchCount: '',
    dinnerCount: '',
    meetAndGreet: '',
    notes: '',
    hotels: '',
    tixSold: '',
    percentSold: 'N/A',
    totalComps: '',
    compsRemain: '0',
    compsUsed: '0'
  }
];